version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: foobar

  wordpress:
    depends_on:
      - db
    build:
      context: ./support
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - wp_root:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: foobar
      WORDPRESS_DB_NAME: wordpress
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db
    environment:
      - PMA_HOST=db
volumes:
  db_data: {}
  wp_root: {}
